# Generated by Django 4.1 on 2023-05-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
