# Generated by Django 4.1 on 2023-05-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_ingredient_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
