# Generated by Django 4.1 on 2023-05-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("cat1", "Category 1"),
                    ("cat2", "Category 2"),
                    ("cat3", "Category 3"),
                ],
                max_length=100,
            ),
        ),
    ]
