# Generated by Django 4.1 on 2023-05-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="amount",
            new_name="quantity",
        ),
    ]
