# Generated by Django 4.1 on 2023-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("cat1", "Semplice"),
                    ("cat2", "Normale"),
                    ("cat3", "Impegnativa"),
                ],
                max_length=100,
            ),
        ),
    ]
