# Generated by Django 4.1 on 2023-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_rename_amount_ingredient_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="recipes", to="recipes.instruction"
            ),
        ),
    ]
