# Generated by Django 4.1 on 2023-06-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_instruction_remove_recipe_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
        ),
    ]
