# Generated by Django 4.2.2 on 2023-06-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
